version: '3.2'

volumes:
  pg-data:
    name: postgres-source-db-pgdata
    driver: local

services:
  postgres-source-db:
    hostname: postgres-source-db
    extra_hosts:
      - "barman: 192.168.100.87"
    container_name: postgres-source-db
    image: postgres-source-db:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: postgres-source-db
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGPORT: "5432"
    ports:
    - "6432:5432"
    - "222:22"
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./data/postgresql/sshkeys
        target: /tmp/.ssh
      - type: bind
        source: ./Postgres/postgresql.conf
        target: /etc/postgresql/postgresql.conf
    command:
      - "postgres"
      - "-c"
      - "wal_level=hot_standby"
      - "-c"
      - "port=5432"
      - "-c"
      - "hba_file=/var/lib/postgresql/config/pg_hba.conf"
      - "-c"
      - "archive_mode=on"
      - "-c"
      - "archive_command=barman-wal-archive -U root --port 222 barman postgres %p"
      - "-c"
      - "max_wal_senders=2"
      - "-c"
      - "max_replication_slots=2"
      - "-c"
      - "log_directory=/var/lib/postgresql/data/log"
      - "-c"
      - "log_filename=postgresql.log"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    restart: always

